/* Native UXP panel; source media and provider credentials never leave this PC. */
const uxp=require('uxp'),bundle=require('./bundle.json');
require('./sync.js').install(ContentriumHost);
const $=id=>document.getElementById(id);
const base='http://localhost:41737';
let credentials=null,state=null,connected=null,mode='separate',job=null,analysisJob=null,analysis=null,plan=null,syncResult=null,syncJob=null,planCameraRefs=[],applying=false,batchRunning=false,stopped=false,applyId=null,polling=false,pending=false;
const microphoneRows=[],cameraRows=[],speakerRows=[],calibrationRows=[],overrideRows=[],syncRows=[];
function say(value){$('status').textContent=value;}
function error(e){say((e.code||'작업 오류')+' · '+(e.message||String(e)));}
function element(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function number(value){const e=element('input');e.type='number';e.value=String(value);return e;}
function options(select,values,empty){select.innerHTML='';if(empty){const e=element('option',empty);e.value='';select.appendChild(e);}for(const [value,label] of values){const e=element('option',label);e.value=value;select.appendChild(e);}}
function label(text,input){const e=element('label',text);e.appendChild(input);return e;}
function basename(path){return path.split(/[\\/]/).pop();}
async function api(path,body,method){const response=await fetch(base+path,{method:method||(body===undefined?'GET':'POST'),headers:{'Content-Type':'application/json',...(credentials?{Authorization:'Bearer '+credentials.token}:{})},...(body===undefined?{}:{body:JSON.stringify(body)})});const value=await response.json();if(!response.ok||value.error&&value.ok===false){const e=new Error(value.error?.message||'요청을 처리할 수 없습니다.');e.code=value.error?.code||'HTTP_'+response.status;throw e;}return value;}
function admitted(){if(!credentials||!connected)throw new Error('먼저 Companion과 현재 시퀀스를 연결하세요.');if(!state?.gateOpen||stopped)throw new Error('업데이트 중에는 편집을 시작할 수 없습니다.');}
function toggle(){for(const el of document.querySelectorAll('input,select,button.mode'))el.disabled=pending||applying||!!job;const locked=!state?.gateOpen||stopped||pending||applying||!!job;for(const id of ['read-project','analyze','sync','plan','apply-sync','apply'])$(id).disabled=locked||!connected||(id==='plan'&&!analysisJob)||(id==='apply'&&!plan)||(id==='apply-sync'&&!syncResult);$('read-project').disabled=!credentials||locked;$('cancel').disabled=!job&&!applying;$('progress').className=job||applying?'running':'';}
async function openCompanion(){try{const result=await uxp.shell.openExternal('contentrium-cut://open','로컬 화자 분석과 업데이트를 위한 Contentrium CUT 앱을 실행합니다.');if(result)throw new Error(result);}catch(e){say('Windows 시작 메뉴에서 Contentrium CUT 앱을 실행하세요. '+String(e));}}
function cameraValues(){return cameraRows.filter(r=>r.role.value!=='protected').map(r=>[r.id,r.title]);}
function mappingInputs(){const values=cameraValues();const old=$('start-camera').value,reserve=$('reserve-camera').value;options($('start-camera'),values);options($('reserve-camera'),values,'지정 안 함');if(values.some(v=>v[0]===old))$('start-camera').value=old;if(values.some(v=>v[0]===reserve))$('reserve-camera').value=reserve;for(const row of speakerRows){const previous=row.select.value;options(row.select,values,'카메라 선택');if(values.some(v=>v[0]===previous))row.select.value=previous;}for(const row of overrideRows)options(row.camera,values);plan=null;toggle();}
function renderSources(){
  for(const id of ['microphones','cameras','calibration','speaker-mapping','sync-sources'])$(id).innerHTML='';microphoneRows.length=cameraRows.length=calibrationRows.length=speakerRows.length=syncRows.length=0;
  const s=connected.snapshot,assets=new Map(s.sources.map(a=>[a.assetId,a]));
  for(const clip of s.clips.filter(c=>c.mediaType==='audio')){
    const row=element('div',undefined,'source-row'),check=element('input');check.type='checkbox';check.checked=microphoneRows.length<(mode==='mixed'?1:2);const title=basename(assets.get(clip.assetId).canonicalPath);const t=element('label',clip.trackRef+' · '+title);t.insertBefore(check,t.firstChild);row.appendChild(t);const fields=element('div',undefined,'row'),speaker=element('input');speaker.value=String.fromCharCode(65+microphoneRows.length);const channel=number(0);fields.appendChild(label('화자 ID',speaker));fields.appendChild(label('채널 · 0부터',channel));row.appendChild(fields);$('microphones').appendChild(row);microphoneRows.push({clip,check,speaker,channel});
    const calibration=element('div',undefined,'row'),first=number(0),last=number(0);calibration.appendChild(label(speaker.value+' 단독 발화 시작',first));calibration.appendChild(label('종료',last));$('calibration').appendChild(calibration);calibrationRows.push({speaker,first,last});
  }
  for(const track of s.tracks.filter(t=>t.mediaType==='video'&&s.clips.some(c=>c.trackRef===t.trackRef))){
    const row=element('div',undefined,'camera-row');const title='V'+(track.index+1)+' · '+track.name;row.appendChild(element('div',title+(track.muted?' · 비활성':''),'source-title'));const fields=element('div',undefined,'row'),role=element('select'),covered=element('input');options(role,[['speaker','화자 카메라'],['wide','전체샷'],['two-shot','투샷'],['reserve','예비'],['protected','보호 · 자막/그래픽']]);covered.placeholder='A, B';role.value=track.muted?'protected':'speaker';fields.appendChild(label('용도',role));fields.appendChild(label('보이는 화자',covered));row.appendChild(fields);$('cameras').appendChild(row);cameraRows.push({id:track.trackRef,track,title,role,covered});role.onchange=mappingInputs;covered.onchange=()=>{plan=null;toggle();};
  }
  const values=[];for(const source of s.sources){const check=element('input');check.type='checkbox';check.checked=true;const text=basename(source.canonicalPath),row=element('label',text);row.insertBefore(check,row.firstChild);$('sync-sources').appendChild(row);syncRows.push({check,source});values.push([source.assetId,text]);}options($('sync-reference'),values);
  renderSpeakers(microphoneRows.filter(r=>r.check.checked).map(r=>r.speaker.value));mappingInputs();
}
function renderSpeakers(ids){$('speaker-mapping').innerHTML='';speakerRows.length=0;for(const id of ids){const select=element('select');options(select,cameraValues(),'카메라 선택');const camera=cameraValues()[speakerRows.length];if(camera)select.value=camera[0];$('speaker-mapping').appendChild(label('화자 '+id,select));speakerRows.push({id,select});select.onchange=()=>{plan=null;toggle();};}}
function microphoneOptions(){return {mode,microphones:microphoneRows.filter(r=>r.check.checked).map(r=>({instanceKey:r.clip.instanceKey,speakerId:r.speaker.value.trim(),channelIndex:Number(r.channel.value)})),speakerCount:Number($('speaker-count').value),vadThreshold:Number($('vad-threshold').value),calibration:calibrationRows.filter(r=>Number(r.last.value)>Number(r.first.value)).map(r=>({speakerId:r.speaker.value.trim(),startFrame:Number(r.first.value),endFrame:Number(r.last.value)}))};}
function mapping(){const s=connected.snapshot;return {speakers:Object.fromEntries(speakerRows.map(r=>[r.id,r.select.value])),cameras:cameraRows.filter(r=>r.role.value!=='protected').map(r=>({cameraId:r.id,role:r.role.value,coveredSpeakers:r.covered.value.split(',').map(v=>v.trim()).filter(Boolean),clips:s.clips.filter(c=>c.trackRef===r.id).map(c=>({instanceKey:c.instanceKey,startFrame:Math.round(Number(c.startTicks)/connected.perFrame),endFrame:Math.round(Number(c.endTicks)/connected.perFrame)}))})),startCameraId:$('start-camera').value,fallbackOrder:$('reserve-camera').value?[$('reserve-camera').value]:[]};}
function policy(){return {minShot:Number($('min-shot').value),shortTurn:Number($('short-turn').value),suppressShort:true,overlap:Number($('overlap').value),overrides:overrideRows.map(r=>({startFrame:Number(r.first.value),endFrame:Number(r.last.value),cameraId:r.camera.value}))};}
async function readProject(){if(applying||job)throw new Error('현재 작업을 마친 뒤 시퀀스를 변경하세요.');connected=await ContentriumHost.snapshot();const s=connected.snapshot;s.hostSnapshotHash=s.snapshotHash;const start=Number($('range-start').value||0),end=Number($('range-end').value||s.range.endFrame);if(!Number.isSafeInteger(start)||!Number.isSafeInteger(end)||start<0||end<=start||end>s.range.endFrame)throw new Error('프레임 범위를 확인하세요.');s.range={startFrame:start,endFrame:end};delete s.snapshotHash;s.snapshotHash=ContentriumHost.hash(s);await api('/project',{snapshot:s,hostIdentity:null});$('project-name').textContent=s.projectName;$('sequence-info').textContent=s.sequenceName+' · '+s.fps.num+'/'+s.fps.den+' fps';$('range-start').value=String(start);$('range-end').value=String(end);analysisJob=analysis=plan=syncResult=null;renderSources();toggle();say('시퀀스가 연결됐습니다. 마이크와 카메라를 지정하세요.');}
function renderPlan(){const s=plan.segments;$('cut-count').textContent=String(s.length);$('review-count').textContent=String(plan.reviews.length);$('timeline').innerHTML='';const bar=element('div',undefined,'timeline');for(const segment of s){const block=element('div');block.style.flex=String(segment.endFrame-segment.startFrame);bar.appendChild(block);}$('timeline').appendChild(bar);$('segments').innerHTML='';for(const segment of s){const row=element('div',undefined,'segment-row');row.appendChild(element('span',segment.startFrame+'–'+segment.endFrame+'f'));row.appendChild(element('span',segment.cameraId+' · '+segment.reason));row.onclick=async()=>{try{await connected.sequence.setPlayerPosition(ContentriumHost.time(String(BigInt(segment.startFrame)*BigInt(connected.perFrame))));say(segment.cameraId+' · '+segment.reasonCodes.join(', '));}catch(e){error(e);}};$('segments').appendChild(row);}$('reviews').innerHTML='';for(const review of plan.reviews)$('reviews').appendChild(element('div',(review.startFrame===undefined?'전체':review.startFrame+'–'+review.endFrame+'f')+' · '+review.code,'review-row'));toggle();}
function addOverride(){if(!connected)return;const row=element('div',undefined,'override-row'),fields=element('div',undefined,'row'),first=number(connected.snapshot.range.startFrame),last=number(connected.snapshot.range.endFrame),camera=element('select');options(camera,cameraValues());fields.appendChild(label('시작',first));fields.appendChild(label('종료',last));row.appendChild(fields);row.appendChild(label('고정 카메라',camera));const remove=element('button','삭제');row.appendChild(remove);const value={first,last,camera};for(const field of [first,last,camera])field.onchange=()=>{plan=null;toggle();};overrideRows.push(value);remove.onclick=()=>{overrideRows.splice(overrideRows.indexOf(value),1);row.remove();plan=null;toggle();};$('overrides').appendChild(row);plan=null;toggle();}
async function refresh(){if(!credentials)return;state=await api('/state');if(!state.gateOpen||state.stopEpoch!==null&&state.stopEpoch!==undefined){stopped=true;plan=null;}else if(!applying)stopped=false;$('pair-section').className='hidden';$('workspace').className='';$('connection').textContent='Premiere Pro · 로컬 엔진 '+state.appVersion;$('models').textContent='Silero: '+state.models.silero.status+' / Community-1: '+state.models['community-1'].status;const required=state.models[mode==='separate'?'silero':'community-1'];$('model-status').textContent=required.status==='ready'?'로컬 모델 준비됨':'모델을 준비한 뒤 분석할 수 있습니다.';const update=state.update;const candidate=update.candidate;$('update-banner').className=candidate&&update.checkState==='AVAILABLE'?'':'hidden';$('update-banner-text').textContent=candidate?'Contentrium CUT '+candidate.appVersion+' 버전을 사용할 수 있습니다.':'';$('update-info').textContent=update.updateState==='IDLE'||update.updateState==='COMPLETE'?(candidate?'새 버전 '+candidate.appVersion+'을 사용할 수 있습니다.':update.checkState==='CURRENT'?'최신 버전입니다.':update.checkState==='NO_RELEASE'?'게시된 업데이트가 없습니다.':update.checkState==='CHECK_FAILED'?'업데이트 확인 실패 · 잠시 후 다시 확인하세요.':'업데이트 확인 중'):update.updateState;$('release-notes').textContent=candidate?.releaseNotes||'';$('update').disabled=!candidate||update.checkState!=='AVAILABLE';toggle();if(!state.gateOpen&&!applying){await api('/updates/ack',{epoch:state.epoch,quiescent:true,batchRunning:false}).catch(()=>{});}}
async function heartbeat(){if(!credentials||!state)return;const receipt=await api('/heartbeat',{hostIdentity:null,epoch:state.epoch,batchRunning,quiescent:!applying,panelVersion:bundle.appVersion,bundleId:bundle.bundleId});if(!receipt.gateOpen||receipt.stopEpoch!==null&&receipt.stopEpoch!==undefined){stopped=true;plan=null;toggle();}}
async function pollJob(){if(!job)return;const value=await api('/jobs/'+job.jobId);if(['running','canceling'].includes(value.status)){say(value.kind==='sync'?'공통 녹음으로 싱크를 분석하고 있습니다.':'로컬에서 화자를 분석하고 있습니다.');return;}const kind=job.kind;job=null;if(value.status==='completed'){if(kind==='analysis'){analysisJob=value.jobId;analysis=value.result;renderSpeakers(analysis.sessionSpeakerIds);say('화자 분석이 끝났습니다. 카메라를 연결한 뒤 편집안을 만드세요.');}else if(kind==='sync'){syncJob=value.jobId;syncResult=value.result;$('sync-result').textContent=JSON.stringify(syncResult,null,2);say('싱크 분석 완료 · 검토가 필요한 소스를 확인하세요.');}}else say(value.status+' · '+(value.error?.code||'작업 중단'));toggle();}
function handler(id,fn){const serial=!['open-companion','open-models','refresh','check-update','update','cancel'].includes(id);$(id).onclick=async()=>{if(serial&&pending)return;if(serial){pending=true;toggle();}try{await fn();}catch(e){error(e);}finally{if(serial)pending=false;toggle();}};}
handler('open-companion',openCompanion);handler('open-models',openCompanion);handler('refresh',refresh);
handler('pair',async()=>{const instanceId='cut-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);credentials=await api('/pair',{code:$('pair-code').value.trim(),instanceId});await uxp.storage.secureStorage.setItem('contentrium-session',JSON.stringify(credentials));$('pair-code').value='';await refresh();await api('/updates/check',{});await refresh();});
handler('read-project',readProject);handler('analyze',async()=>{admitted();job=await api('/jobs',{kind:'analysis',options:microphoneOptions(),epoch:state.epoch});plan=analysis=null;analysisJob=null;toggle();});
handler('sync',async()=>{admitted();const assetIds=syncRows.filter(r=>r.check.checked).map(r=>r.source.assetId);job=await api('/jobs',{kind:'sync',options:{assetIds,reference:$('sync-reference').value},epoch:state.epoch});syncResult=null;toggle();});
handler('plan',async()=>{admitted();const currentMapping=mapping(),snapshotHash=connected.snapshot.snapshotHash,epoch=state.epoch;const nextPlan=await api('/plan',{jobId:analysisJob,mapping:currentMapping,policy:policy(),epoch});if(stopped||!state.gateOpen||state.epoch!==epoch||connected?.snapshot.snapshotHash!==snapshotHash)throw new Error('PLAN_STALE');plan=nextPlan;planCameraRefs=currentMapping.cameras.map(c=>c.cameraId);renderPlan();say(plan.reviews.length?'검토 사항 '+plan.reviews.length+'개를 확인하세요.':'편집안을 검토한 뒤 Premiere에 적용하세요.');});
handler('add-override',addOverride);
handler('apply',async()=>{admitted();const approved=await api('/apply/begin',{planHash:plan.planHash,snapshotHash:connected.snapshot.snapshotHash,epoch:state.epoch});applyId=approved.applyId;applying=true;stopped=false;toggle();const refs=planCameraRefs.slice();try{const result=await ContentriumHost.apply(approved.plan,connected.snapshot,refs,{stopped:()=>stopped,onBatch:value=>{batchRunning=value;},check:async()=>{await api('/apply/check',{applyId,epoch:approved.epoch});if(stopped)throw new Error('CANCELED');},onResult:sequenceRef=>{say('결과 시퀀스에 영상 컷을 적용하고 있습니다.');}});await api('/apply/end',{applyId,status:'completed',receipt:{planHash:approved.plan.planHash,sourceUnchanged:result.originalUnchanged,readback:{verified:result.audioAndOverlaysUnchanged},resultSequenceRef:result.sequenceRef}});say('적용 완료 · '+result.sequenceName+' / 원본·오디오 보존 확인');plan=null;}catch(e){await api('/apply/end',{applyId,status:'canceled',receipt:{resultSequenceRef:e.resultSequenceRef}}).catch(()=>{});throw e;}finally{applying=batchRunning=false;applyId=null;await refresh();}});
handler('cancel',async()=>{stopped=true;if(job)await api('/jobs/'+job.jobId+'/cancel',{});if(applyId)await api('/apply/end',{applyId,status:'canceled'});say('작업 중단 요청 · 현재 트랜잭션 뒤 추가 편집을 멈춥니다.');});
handler('check-update',async()=>{await api('/updates/check',{});await refresh();});
handler('update',async()=>{const candidate=state.update.candidate;if(!candidate)throw new Error('업데이트를 다시 확인하세요.');stopped=true;plan=null;toggle();say('모든 Contentrium CUT 작업을 중단하고 업데이트를 시작합니다.');await api('/updates/start',{candidateId:candidate.candidateId,manifestDigest:candidate.manifestDigest,requestId:'update-'+Date.now()});await refresh();});
handler('apply-sync',async()=>{admitted();const assets=new Set(syncRows.filter(r=>r.check.checked).map(r=>r.source.assetId));const keys=connected.snapshot.clips.filter(c=>assets.has(c.assetId)).map(c=>c.instanceKey);const syncPlan=await api('/sync-plan',{jobId:syncJob,selectedClipInstanceKeys:keys,epoch:state.epoch});const approved=await api('/apply/begin',{planHash:syncPlan.planHash,snapshotHash:connected.snapshot.snapshotHash,epoch:state.epoch});applyId=approved.applyId;applying=true;stopped=false;toggle();try{const result=await ContentriumHost.applySync(approved.plan,connected.snapshot,{stopped:()=>stopped,onBatch:v=>{batchRunning=v;},check:async()=>{await api('/apply/check',{applyId,epoch:approved.epoch});if(stopped)throw new Error('CANCELED');}});await api('/apply/end',{applyId,status:'completed',receipt:{planHash:approved.plan.planHash,sourceUnchanged:result.originalUnchanged,readback:{verified:result.readbackVerified},resultSequenceRef:result.sequenceRef}});say('싱크 적용 완료 · '+result.sequenceName+' / 원본 보존 확인');syncResult=null;connected=null;}catch(e){await api('/apply/end',{applyId,status:'canceled',receipt:{resultSequenceRef:e.resultSequenceRef}}).catch(()=>{});throw e;}finally{applying=batchRunning=false;applyId=null;await refresh();}});
for(const value of ['separate','mixed'])handler('mode-'+value,async()=>{mode=value;for(const other of ['separate','mixed'])$('mode-'+other).className='mode'+(mode===other?' active':'');analysisJob=analysis=plan=null;if(connected)renderSources();await refresh();});
for(const id of ['range-start','range-end'])$(id).onchange=()=>{connected=null;plan=analysis=analysisJob=null;toggle();say('범위가 바뀌었습니다. 현재 시퀀스를 다시 연결하세요.');};
for(const id of ['min-shot','short-turn','overlap'])$(id).onchange=()=>{plan=null;toggle();};
$('version').textContent=bundle.appVersion;
(async()=>{try{const saved=await uxp.storage.secureStorage.getItem('contentrium-session');credentials=JSON.parse(new TextDecoder().decode(saved));await refresh();await api('/updates/check',{});await refresh();}catch(e){credentials=null;$('pair-section').className='';$('workspace').className='hidden';say('Contentrium CUT 앱을 실행하고 연결 코드를 입력하세요.');}toggle();})();
setInterval(async()=>{if(polling||!credentials)return;polling=true;try{await heartbeat();await pollJob();await refresh();}catch(e){$('connection').textContent='로컬 엔진 연결 대기';if(e.code==='AUTH_REQUIRED'){credentials=null;$('pair-section').className='';$('workspace').className='hidden';}if(job||applying){stopped=true;error(e);}}finally{polling=false;}},1000);

$('update-banner-button').onclick=()=>$('update').onclick();
