/* Unshipped harness: mutations are restricted to our generated test project. */
require('./sync.js').install(ContentriumHost);
const H=ContentriumHost,P=H.ppro,$=id=>document.getElementById(id);
const config=require('./qa-config.js'),qaGuard=require('./qa-guard.js');
let live,result,ownedProjectRef;
async function proof(event,value){await fetch('http://localhost:41738/proof',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({event,value})});$('status').textContent=event+'\n'+JSON.stringify(value,null,2);}
async function owned(){const s=await H.snapshot();ownedProjectRef=qaGuard.verify(s,config,ownedProjectRef);return s;}
function button(id,run){$(id).onclick=async()=>{try{$('status').textContent='Running '+id;await run();}catch(e){await proof('ERROR',{operation:id,message:String(e),stack:e.stack,resultSequenceRef:e.resultSequenceRef});}};}
function ownedControl(){return {check:async()=>{await owned();},beforeBatch:async b=>{await owned();await proof('QA_BATCH_INTENT',b);return {execute:true};},afterBatch:async b=>{await proof('QA_BATCH_RETURNED',b);},onResult:async sequenceRef=>{await proof('QA_RESULT',{sequenceRef});}};}
button('fixture',async()=>{const created=await H.createFixture(config.paths,config.projectPath);await owned();await proof('FIXTURE',created);});
button('read',async()=>{live=await owned();const values=[];for(const [key,item] of live.objects){const chain=await item.getComponentChain(),components=[];for(let i=0;i<chain.getComponentCount();i++){const c=chain.getComponentAtIndex(i),params=[];for(let j=0;j<c.getParamCount();j++){const p=c.getParam(j);params.push({index:j,name:p.displayName,value:await p.getValueAtTime(P.TickTime.TIME_ZERO),keyframes:p.getKeyframeListAsTickTimes().map(t=>String(t.ticks)),supported:await p.areKeyframesSupported()});}components.push({matchName:await c.getMatchName(),params});}values.push({key,components});}await proof('READ',{snapshot:live.snapshot,components:values});});
// Selected-source acceptance must use the installed product panel and its real
// service capability/journal. This host-only harness cannot grant that evidence.
button('apply',async()=>{live=await owned();if(live.snapshot.range.endFrame!==108000)throw new Error('QA_60_MIN_REQUIRED');
  const camera=live.snapshot.clips.filter(c=>c.mediaType==='video').slice(0,3);if(camera.length!==3)throw new Error('QA_CAMERAS_REQUIRED');
  for(const clip of camera){const item=live.objects.get(clip.instanceKey),chain=await item.getComponentChain();let target;for(let i=0;i<chain.getComponentCount();i++){const c=chain.getComponentAtIndex(i);if(!/opacity/i.test(await c.getMatchName()))continue;for(let j=0;j<c.getParamCount();j++){const p=c.getParam(j);if(await p.areKeyframesSupported()&&typeof (await p.getValueAtTime(P.TickTime.TIME_ZERO)).value==='number'){target=p;break;}}}if(!target)throw new Error('QA_OPACITY_PARAM_REQUIRED');const k0=target.createKeyframe(100),k1=target.createKeyframe(90);k0.position=P.TickTime.TIME_ZERO;k1.position=H.time(String(254016000000n*3600n));H.transaction(live.project,'Owned QA keyed opacity',c=>{c.addAction(target.createSetTimeVaryingAction(true));c.addAction(target.createAddKeyframeAction(k0));c.addAction(target.createAddKeyframeAction(k1));});}
  live=await owned();const source=live.objects.get(camera[0].instanceKey),editor=P.SequenceEditor.getEditor(live.sequence);H.transaction(live.project,'Owned QA protected overlay',c=>c.addAction(editor.createCloneTrackItemAction(source,P.TickTime.TIME_ZERO,3,0,true,false)));const overlay=(await live.sequence.getVideoTrack(3)).getTrackItems(P.Constants.TrackItemType.CLIP,false)[0];H.transaction(live.project,'Owned QA overlay disabled',c=>c.addAction(overlay.createSetDisabledAction(true)));await live.project.save();live=await owned();
  const refs=['video:0','video:1','video:2'],frames=[0,27000,54000,81000,108000],segments=[];for(let i=0;i<4;i++){const clip=live.snapshot.clips.find(c=>c.trackRef===refs[i%3]);segments.push({startFrame:frames[i],endFrame:frames[i+1],cameraId:clip.trackRef,sourceClipInstanceKey:clip.instanceKey,sourceIn:String(BigInt(frames[i])*BigInt(live.perFrame)),sourceOut:String(BigInt(frames[i+1])*BigInt(live.perFrame)),reason:'OWNED_QA',reasonCodes:['OWNED_QA']});}
  const plan={schemaVersion:1,snapshotHash:live.snapshot.snapshotHash,segments};plan.planHash=H.hash(plan);const before=live.snapshot;result=await H.apply(plan,before,refs,ownedControl());await proof('APPLY_60_MIN',{before,result});
});
button('export',async()=>{if(!result||!live)throw new Error('QA_APPLY_REQUIRED');await owned();const target=await H.resolveInput(result.snapshot);qaGuard.verify(target,config,ownedProjectRef);const frames=[0,26999,27000,53999,54000,80999,81000,107999];for(const frame of frames){if(!await P.Exporter.exportSequenceFrame(target.sequence,H.time(String(BigInt(frame)*BigInt(target.perFrame))),'round2-frame-'+frame+'.png',config.exportPath,320,180))throw new Error('QA_FRAME_EXPORT_FAILED');}const preset='C:\\Program Files\\Adobe\\Adobe Premiere Pro 2026\\Settings\\EncoderPresets\\Wave48mono16.epr';const manager=P.EncoderManager.getManager();for(const [name,sequence] of [['before',live.sequence],['after',target.sequence]]){if(!await manager.exportSequence(sequence,P.Constants.ExportType.IMMEDIATELY,config.exportPath+'\\round2-audio-'+name+'.wav',preset,true))throw new Error('QA_PCM_EXPORT_FAILED');}await proof('EXPORT_60_MIN',{frames,audio:['round2-audio-before.wav','round2-audio-after.wav']});});
